import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./_components/Navbar";
import { Toaster } from "sonner";
import { Suspense } from "react";
import { getUser } from "./actions/getUser";
import { SafeUser } from "./types";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const rawUser = await getUser();
  const currentUser: SafeUser | null = rawUser && !("ok" in rawUser) && rawUser.id ? {
    id: rawUser.id,
    name: rawUser.name ?? undefined,
    email: rawUser.email ?? undefined,
    image: rawUser.image ?? undefined,
    favoriteIds: rawUser.favoritesIds ?? [],
  } : null;

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Navbar currentUser={currentUser} />
        <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        <Toaster />
      </body>
    </html>
  );
}
